NAME = fillit

CFILES = check_file.c ft_backtraking.c ft_concat_str.c ft_putfinalboard.c get_coords.c main.c valid_tetrimino.c libft/*.c

FLAGS = -Wall -Wextra -Werror

HFILE = -I. -I./libft/libft.h

all:
	gcc $(FLAGS) $(HFILES) -c $(CFILES)
	gcc $(FLAFS) *.o -o $(NAME)

clean: 
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

